### ISSUE TITLE
HW3 text analysis question

### ISSUE THREAD

**Issue by arschw** [uchicago-codes/MPCS50101-2017-Winter-Forum#24]
Hi!

I am currently working on the text analysis problem and have been trying to remove punctuation. However, what I am finding is that there are some weird characters that are UTF-8, that do not get removed such as the weird single quote (apostrophe). 

When I try to use .split() to create a list of the words, I can see the them decoded as \xe2\x80\x99, is there any way to easily map these characters over to similar ascii characters?

Thanks,
Andrew

**Comment by rkillackey** [comment]
Hi Andrew,

The issue here appears to be with the way the file is encoded, as I believe you've discovered. One approach to this problem could be to use regular expressions to search for these characters. Check out the method `re.sub` in the `re` library to help out with that. From there you could either remove the character or replace it with the ASCII character. Another approach could be to use the `decode` or `encode` methods to change the encoding and call replace on the characters. 

Hope this helps!

**Comment by tabinks** [comment]
Rachel is correct that are ways to remove the characters and/or encode them in a different format.  For this assignment, you do not need to do that.  Since what we are interested in is the unique word, there is no need to worry about the single occurrence of an unusual character.  Just treat this word "as is" and count it

For example, for the word `na\xc3\xafve`, just treat that as a word.  It will not impact your final results since we only see it a single time. 

This is a a good example of how something seemingly straightforward like text processing can become very complicated.
