### ISSUE TITLE
HW6 Problem 4

### ISSUE THREAD

**Issue by sschwartz1** [uchicago-codes/MPCS50101-2017-Winter-Forum#59]
Should problem 4 be in an object oriented programming style?

**Comment by nickflees** [comment]
My interpretation is that it could be written as a main() method using the fractions module that you're creating for number 3.

**Comment by sschwartz1** [comment]
Should we assume that the user enters a correct input (i.e. "4/5") or should we assume the user can input anything to try and break the program? Also should the fractions that we are testing the user on always be less than 1?

**Comment by nickflees** [comment]
You should implement some error checking. I don't think you should assume that the fractions will be less than 1, but I'll defer to @tabinks on a final answer.

**Comment by ddeng50101** [comment]
same question as sschwartz - though I wrote the code assuming the user enters in the correct format...

**Comment by nickflees** [comment]
Others are free to weigh in here, but I think the bulk of the implementation will be in an object-oriented style because you're asked to do that in problem 3. Problem 4 is a continuation of problem 3 and therefore necessarily uses an object-oriented approach. Past that point, I can envision pretty solid implementations that do either of the following:
1. Write a game class that uses the Fraction class.
2. Write a script that handles gameplay in a main method and uses the Fraction class.

In #62, I discuss some possible considerations for implementing the game as a class.

**Comment by tabinks** [comment]
In this problem, we are not trying to break your code...this is just to practice working with classes.  You should not assume the the fraction will be less than one.  Your class should be able to handle, for example, 5/2 and be able to work with that number and eventually, if needed, print the reduced form.

**Comment by tabinks** [comment]
I think @nickflees presented a good way to address the problem.  The "main game loop" can be procedural while the fraction objects should be designed and implemented in a object oriented manner.

**Comment by ddeng50101** [comment]
Thanks Andrew. 

quick follow up q = for 5/2, should the program print 21/2 or 2&1/2?

**Comment by nickflees** [comment]
@ddeng50101, for what it's worth, I've been recommending that a mixed fraction be printed as
2 1/2

(with a single space separating the whole component from the numerator of the fractional component).
