### ISSUE TITLE
HW Question

### ISSUE THREAD

**Issue by ccodette** [uchicago-codes/MPCS50101-2017-Winter-Forum#62]
Hi,
When using counter variables with a recursive function, is it sometimes prudent to make them global and instantiate them outside of the function?
Thanks,
Chris

**Comment by nickflees** [comment]
In general, I would caution against that. Without knowing what you're planning to do, it sounds like it may not be the optimal approach to the problem. My gut reaction is split into two thoughts:

1. If you're counting, recursion probably isn't the answer.
2. If you insist on counting and using recursion, I would write the function so that it takes an argument that represents the counter and increments it every time the function is called.

Can you give some more context for what you're trying to do?

**Comment by nickflees** [comment]
I'm going to back off of that a little to say that there are probably some legitimate reasons to recurse and count, but it's also probably true that you should pass the counter to the function on which you're recursing.

**Comment by ccodette** [comment]
Tallying correct and incorrect answers... I am a calling a function within itself if user chooses to answer another question. "Correct"/"Incorrect" are incremented before the call, but reset to 0 when the function runs again, if they are instantiated at 0 within the function. It works if I place the counters outside the function and make them global, but it seems like there must be a better way to do it.

**Comment by nickflees** [comment]
Ok. You should probably be able to avoid recursion to get this done. I would recommend building the gameplay into a class. The class can have a method called "play" or something like that, which, when called, runs the game logic once. At the end, you can give the user the option to play again and call the play method again accordingly. The instances of the class can have an attribute that acts as a counter of the number of times the game has been played. Your play method could increment the counter each time it's called.

**Comment by nickflees** [comment]
Update. You can add attributes to reflect correct and incorrect answers too and update those accordingly. You can use the play count to calculate a percentage correct.

**Comment by ccodette** [comment]
Thanks; I'll give it a try.
