### ISSUE TITLE
Problem 5

### ISSUE THREAD

**Issue by ddeng50101** [uchicago-codes/MPCS50101-2017-Winter-Forum#67]
After I write the code using jupyter notebook (and test that the code runs fine), if i save it in a notebook format (.ipynb) and try to run it in terminal, it generates an error message. Should I save in in another format...?

**Comment by nickflees** [comment]
The .ipynb file is not a Python script. I believe it's in a .json format. If you try to run it as a Python script, it fails because it's not Python, but rather another format entirely, with Python code stored in it as strings. If you want to run the code that you've written in the Jupyter notebook, you'll need to extract the Python code by itself and save it separately.

**Comment by ddeng50101** [comment]
for the homework, should we submit a .py file?

**Comment by nickflees** [comment]
You can submit your .ipynb file.

**Comment by ddeng50101** [comment]
Thanks!
