### ISSUE TITLE
HW 8 #2

### ISSUE THREAD

**Issue by arichards33** [uchicago-codes/MPCS50101-2017-Winter-Forum#91]
Are we supposed to do something different with this question, or is the answer supposed to be O(nlogn)? 

"I suppose the task of compiling a telephone or address book from a list of names/numbers might be O(n log n)"

**Comment by alexichryss** [comment]
Think of the value of that statement.

**Comment by nickflees** [comment]
Hey @arichards33. My interpretation is that for this problem you should think about why compiling a list of phone numbers might be O(n * lg n) and then write an explanation. That's my best guess as to what @alexichryss means above too. (Please correct me if I'm wrong, by the way, Alexi).

**Comment by alexichryss** [comment]
@nickflees It has been since edited, but my original answer was pertaining to the supposition stated. The value of a supposition is True or False. Assessing that value is an O(1) order of complexity. At least, that's how I interpreted the question, seeing as it already gave the correct answer.

The question has since changed, so I guess I'll update my repo accordingly.

**Comment by tabinks** [comment]
@alexichryss Yeah. I mistakenly left the answer there.  I changed the site for those who didn't notice (or start yet).
