### ISSUE TITLE
Question in Problem 3: using binary search to find max

### ISSUE THREAD

**Issue by Gloria-Xiaolu-Zhang** [uchicago-codes/MPCS50101-2017-Winter-Forum#98]
In Problem 3, we are asked to compare the speed of Reduce, Linear Search and Binary Search to find max in an array. But do we need a sorted list to conduct binary search? And after the list is sorted, the max is just the last number (assuming ascending). 

So, does it mean the main operation of using binary search to find max is to sort the list?

Thank you!

**Comment by tabinks** [comment]
@Gloria-Xiaolu-Zhang Yes, you will need to use a sorted list to do a binary search.  You should factor the time required to do this into you overall assessment.

**Comment by bmbeller** [comment]
Following up here- so is it sufficient just to look for the last number in a sorted list for the "binary search" function?

**Comment by nickflees** [comment]
@bmbeller I think your intuition is right. In order to get meaningful results from a binary search, we require a sorted collection. Since we have a sorted collection, we know that the last element will have a value greater than or equal to all other elements, so finding the maximal value is trivial.
